### PR TITLE
English formulation fix

### PR DESCRIPTION
**Pull request by Plavit**
This has really bugged me all year - I hope I got the syntax correctly, but please fix this <3

### CODE REVIEW

**Comment by krulis-martin** [comment]
Normally, we appreciate PRs that fix things with great enthusiasm. However, I do not think the "of which" phrase is used correctly here as it alters the meaning of the sentence. Please, rephrase it.

Furthermore, I do not see how this could have bugged you all year. These particular sentences were not present in 1.x versions and ReCodEx 2.0 was released two month ago.

**Comment by Plavit** [comment]
> Normally, we appreciate PRs that fix things with great enthusiasm. However, I do not think the "of which" phrase is used correctly here as it alters the meaning of the sentence. Please, rephrase it.
> 
> Furthermore, I do not see how this could have bugged you all year. These particular sentences were not present in 1.x versions and ReCodEx 2.0 was released two month ago.

Hello! Firstly, I hope my PR did not cause any offence. I apologize that my formulations were inaccurate (all year was referring to this academic year, which is two months indeed). It was meant in more of a joking way but in retrospect I see how this can also be taken as direct critique - which it was not meant to be, recodex is generally in an excellent state! I hope you accept my apology for this miscommunication.

Additionally I realize this is a low priority enhancement, so please feel no huge pressure from my side on this issue, but I do offer my help if appropriate and applicable.

More to the point, my understanding from the GUI is that the sentence refers to (un) hidden assignments that have deadlines in the past. Due to the sentence structure including the number of assignments at the beginning, I see a few alternatives:
1) X assignments hidden with deadlines in the past (ok but seems awkward to me)
2) X assignments hidden the deadlines of which have passed (chosen variant)
3) X assignments past their deadline (also possible, maybe the original was a typo of this version?)

I'll be happy to change the PR to reflect any of the above options, all of which are in my opinion more correct than "assignments pass deadline". Will be happy to hear your thoughts and feedback.

**Comment by krulis-martin** [comment]
No offense taken, I was just nitpicking. As I said, we welcome PRs.
The "of which" does not sit right as it also suggests a subset, Version 3. was the original intent.

**Comment by Plavit** [comment]
@krulis-martin Could you review changes introduced in f2bf250 if it solves the issue well enough?

**Comment by krulis-martin** [comment]
Much better, thanks.

**Review by krulis-martin — APPROVED** [review]

**Pull request merged**
