### PR TITLE
Show notification if there is a problem downloading the file with logs

### PR DESCRIPTION
**Pull request by simonrozsival**

### CODE REVIEW

**Comment by Neloop** [comment]
Please make this more general even for this files: https://github.com/ReCodEx/web-app/commit/345ba3a9d9a9159e8b8498375e6be746c444d62c#diff-426954644ad96b22e9c86d41cea36c57R24

**Comment by Neloop** [comment]
and this files: https://github.com/ReCodEx/web-app/blob/master/src/redux/modules/referenceSolutionEvaluations.js#L31

**Comment by simonrozsival** [comment]
I will try to fix the tests today in the evening.

**Comment by simonrozsival** [comment]
Yep, then it must be an argument.

**Pull request merged**
